version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./creditcardactivity
      command: /code/initserver.sh
      volumes:
        - ./creditcardactivity:/code
      depends_on:
        - db
  web:
      build: ./creditcardactivity
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./creditcardactivity:/code
      ports:
        - "8000:8000"
      expose:
        - "8000"
      depends_on:
        - web-init

volumes:
   data-volume: