version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=pomelo
        - POSTGRES_PASSWORD=pomelopswd
      ports:
        - "5432:5432"
      volumes:
            - data-volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dummy@duke.edu
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  web-init:
      build: ./creditcardactivity
      command: /code/initserver.sh
      volumes:
        - ./creditcardactivity:/code
      depends_on:
        - db
  web:
      build: ./creditcardactivity
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./creditcardactivity:/code
      ports:
        - "8000:8000"
      expose:
        - "8000"
      depends_on:
        - web-init

volumes:
   data-volume: