# Generated by Django 4.2.7 on 2023-11-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_amount_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_transaction',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
